# theme: jekyll-theme-slate
remote_theme: just-the-docs/just-the-docs@main
plugins:
  - jekyll-remote-theme

title: SounDoer
description: [SounDoer.com]

color_scheme: dark

search_enabled: false

exclude:
  - private
